name: Node.js CI

on: [push]

jobs:
  build-and-test-server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
        working-directory: ./server
      - run: npm run build --if-present
        working-directory: ./server
      - run: npm test
        working-directory: ./server

  build-and-test-client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
        working-directory: ./client
      - run: npm run build --if-present
        working-directory: ./client
      - run: npm test
        working-directory: ./client
